## EnergyDome

- type: latheRecipe
  id: EnergyDomeTurtle
  result: EnergyDomeTurtle
  completetime: 12
  materials:
    Steel: 1000
    Plastic: 500
    Silver: 150

## Weapons

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponIonRifle
  result: WeaponIonRifle
  materials:
    Steel: 2000
    Glass: 1000
    Gold: 1000
    Silver: 500

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponIonCarbine
  result: WeaponIonCarbine
  materials:
    Steel: 1500
    Gold: 1000
    Silver: 1000

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponLaserImmolator
  result: WeaponLaserImmolator
  materials:
    Steel: 2000
    Plasma: 1000
    Silver: 1000

- type: latheRecipe
  parent: BaseWeaponRecipeLong
  id: WeaponDecloner
  result: WeaponDecloner
  materials:
    Steel: 2500
    Glass: 2500
    Plasma: 2500
    Silver: 2500
    Gold: 1000
    Diamond: 1000

#Cybernetics
- type: latheRecipe
  id: LeftArmCyberBulwark
  result: LeftArmCyberBulwark
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 450
    Steel: 450
    Silver: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: RightArmCyberBulwark
  result: RightArmCyberBulwark
  categories:
  - Cyberlimbs
  completetime: 10
  materials:
    Plastic: 450
    Steel: 450
    Silver: 100
    Glass: 100
    Plasma: 100

- type: latheRecipe
  id: MagazineGrenadeEMP
  result: MagazineGrenadeEMP
  completetime: 6 # one second per grenade
  materials:
    Plastic: 600
    Steel: 1200
    Uranium: 600
    Plasma: 600

- type: latheRecipe
  id: MagazineGrenadeBaton
  result: MagazineGrenadeBaton
  completetime: 6
  materials:
    Plastic: 600
    Steel: 1650

- type: latheRecipe
  id: MagazineGrenadeFlash
  result: MagazineGrenadeFlash
  completetime: 6
  materials:
    Plastic: 1650
    Steel: 1200
    Glass: 600

- type: latheRecipe
  id: MagazineGrenadeBlast
  result: MagazineGrenadeBlast
  completetime: 6
  materials:
    Plastic: 600
    Steel: 1200
    Uranium: 300

- type: latheRecipe
  id: MagazineGrenadeFrag
  result: MagazineGrenadeFrag
  completetime: 6
  materials:
    Plastic: 600
    Steel: 2000