- type: borgPaint
  id: SecurityBasic
  name: Basic
  spritePath: _Starlight/Mobs/Silicon/Chassis/security.rsi

- type: borgPaint
  id: SecurityRedKnight
  name: Red Knight
  spritePath: _Starlight/Mobs/Silicon/Chassis/security.rsi
  spriteBodyState: red-knight
  spriteHasMindState: red-knight_e
  spriteNoMindState: red-knight_e_r
  spriteToggleLightState: red-knight_l

- type: borgPaint
  id: SecurityBlackKnight
  name: Black Knight
  spritePath: _Starlight/Mobs/Silicon/Chassis/security.rsi
  spriteBodyState: black-knight
  spriteHasMindState: black-knight_e
  spriteNoMindState: black-knight_e_r
  spriteToggleLightState: black-knight_l

- type: borgPaint
  id: SecurityStandard
  name: Standard
  spritePath: _Starlight/Mobs/Silicon/Chassis/security.rsi
  spriteBodyState: standard
  spriteHasMindState: standard_e
  spriteNoMindState: standard_e_r
  spriteToggleLightState: standard_l

- type: borgPaint
  id: SecurityNoble
  name: Noble-SEC
  spritePath: _Starlight/Mobs/Silicon/Chassis/security.rsi
  spriteBodyState: noble
  spriteHasMindState: noble_e
  spriteNoMindState: noble_e_r
  spriteToggleLightState: noble_l

- type: borgPaint
  id: SecurityCricket
  name: Cricket
  spritePath: _Starlight/Mobs/Silicon/Chassis/security.rsi
  spriteBodyState: cricket
  spriteHasMindState: cricket_e
  spriteNoMindState: cricket_e_r
  spriteToggleLightState: cricket_l

- type: borgPaint
  id: SecurityHeavy
  name: Heavy
  spritePath: _Starlight/Mobs/Silicon/Chassis/security.rsi
  spriteBodyState: heavy
  spriteHasMindState: heavy_e
  spriteNoMindState: heavy_e_r
  spriteToggleLightState: heavy_l