- type: entity
  id: CrateServiceHydraRefill
  parent: CratePlastic
  name: hydra refill crate
  description: Contains two refills for the Hydra cleanade launcher.
  components:
  - type: StorageFill
    contents:
      - id: GrenadeCleanade
        amount: 12

- type: entity
  id: CrateServiceHydra
  parent: CratePlastic
  name: hydra crate
  description: Contains a Hydra grenade launcher with four spare grenades.
  components:
  - type: StorageFill
    contents:
      - id: GrenadeCleanade
        amount: 4
      - id: WeaponLauncherHydra
        amount: 1